export interface Segment {
  id: string;
  startTime: number;
  endTime: number;
  speaker: string;
  text: string;
}

export interface Insight {
  id: string;
  type: 'SUMMARY' | 'ACTION_ITEM' | 'REQUIREMENT' | 'QUESTION';
  content: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  referencedTime?: number;
}

export interface Meeting {
  id: string;
  title: string;
  createdAt: string;
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';
  segments: Segment[];
  insights: Insight[];
  chats: ChatMessage[];
}

export const MOCK_MEETINGS: Meeting[] = [
  {
    id: '1',
    title: 'Transcripto Cloud Architecture Strategy',
    createdAt: 'July 19, 2026',
    status: 'COMPLETED',
    segments: [
      { 
        id: 's1', startTime: 0, endTime: 45, speaker: 'Speaker A', 
        text: 'Alright, let\'s dive into the core architecture. We need a system that can handle 30-minute to one-hour long meeting recordings without timing out the main API thread. I was thinking we offload the heavy lifting to a background queue system. If we don\'t do this, the user\'s browser is just going to sit there spinning while FFmpeg extracts the audio, which is a terrible experience.' 
      },
      { 
        id: 's2', startTime: 45, endTime: 110, speaker: 'Speaker B', 
        text: 'I completely agree. BullMQ backed by Redis is probably our best bet for the background processing. It handles retries gracefully and we can set it up inside our monorepo as a separate package. The API will simply acknowledge the file upload, push the job to Redis, and instantly return a 201 Created status to the frontend. From there, the Next.js app can poll or listen to webhooks to update the UI from "Pending" to "Processing" to "Completed".' 
      },
      { 
        id: 's3', startTime: 110, endTime: 185, speaker: 'Speaker A', 
        text: 'Exactly. Once the file is in the queue, the worker picks it up. Step one is FFmpeg audio extraction. Step two is pushing that audio to the Whisper API for transcription. The transcription gives us these timestamped segments. But we also need to chunk that text, generate embeddings using OpenAI\'s embedding models, and store them in PostgreSQL. We\'ll use the pgvector extension for that, which gives us fast nearest-neighbor search for the RAG chat features.' 
      }
    ],
    insights: [
      { id: 'i1', type: 'SUMMARY', content: 'Agreed on decoupling heavy processing via BullMQ/Redis to prevent API timeouts.' },
      { id: 'i2', type: 'REQUIREMENT', content: 'Use PostgreSQL with pgvector for storing embedding chunks to enable RAG chat.' },
      { id: 'i3', type: 'ACTION_ITEM', content: 'Set up a dedicated @transcripto/jobs package in the monorepo.' },
      { id: 'i4', type: 'QUESTION', content: 'Should we run Redis on a separate dedicated instance or use a managed service like Upstash?' },
      { id: 'i5', type: 'SUMMARY', content: 'The background queue ensures the API instantly returns a 201 Created.' },
      { id: 'i6', type: 'ACTION_ITEM', content: 'Implement polling or webhook listener on the Next.js frontend to monitor queue status.' },
      { id: 'i7', type: 'REQUIREMENT', content: 'FFmpeg must be configured correctly in the worker environment to extract audio before transcription.' }
    ],
    chats: [
      { id: 'c1', role: 'user', content: 'What background queue library was suggested?' },
      { id: 'c2', role: 'assistant', content: 'Speaker B suggested using BullMQ backed by Redis for handling the background processing. This prevents the API from timing out during heavy FFmpeg extraction.', referencedTime: 45 },
      { id: 'c3', role: 'user', content: 'Why do we need pgvector?' },
      { id: 'c4', role: 'assistant', content: 'Speaker A mentioned pgvector is needed to store the text chunk embeddings generated by OpenAI models. It provides fast nearest-neighbor search, which is essential for powering these RAG chat features.', referencedTime: 110 },
      { id: 'c5', role: 'user', content: 'Does the frontend wait for the transcription to finish?' },
      { id: 'c6', role: 'assistant', content: 'No, Speaker B noted that the API instantly returns a 201 Created status after pushing the job to Redis. The Next.js app will then either poll or use webhooks to update the UI status.', referencedTime: 45 },
      { id: 'c7', role: 'user', content: 'Who is handling the frontend polling implementation?' },
      { id: 'c8', role: 'assistant', content: 'The transcript does not explicitly state who will handle the frontend implementation. Speaker B simply mentions that the Next.js app can poll or listen to webhooks.', referencedTime: 45 },
      { id: 'c9', role: 'user', content: 'Can we use regular Postgres without pgvector?' },
      { id: 'c10', role: 'assistant', content: 'Speaker A specifically emphasized the need for the pgvector extension because it provides fast nearest-neighbor search capabilities, which regular Postgres does not offer natively for embeddings.', referencedTime: 110 },
      { id: 'c11', role: 'user', content: 'Are there any security concerns mentioned with Redis?' },
      { id: 'c12', role: 'assistant', content: 'There are no security concerns regarding Redis mentioned in this segment of the meeting. The discussion focused purely on its use as a resilient backing store for BullMQ.', referencedTime: 45 },
      { id: 'c13', role: 'user', content: 'What is the exact chunking strategy for embeddings?' },
      { id: 'c14', role: 'assistant', content: 'The exact chunking strategy (e.g., token size or overlap) was not specified. Speaker A only noted that they need to "chunk that text" before generating embeddings.', referencedTime: 110 },
      { id: 'c15', role: 'user', content: 'Excellent, summarize the entire architecture plan.' },
      { id: 'c16', role: 'assistant', content: '1. API receives file and offloads to BullMQ (Redis).\n2. API returns 201 Created instantly.\n3. Background worker uses FFmpeg for audio extraction.\n4. Audio sent to Whisper API for transcription.\n5. Transcript text is chunked and embedded via OpenAI.\n6. Embeddings stored in PostgreSQL via pgvector for RAG chat.\n7. Frontend Next.js app updates UI via polling/webhooks.', referencedTime: 110 }
    ]
  }
];
